# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Cell_estimatedHeight' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cell_estimatedHeight

  target 'Cell_estimatedHeightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cell_estimatedHeightUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Masonry'
end
